### ISSUE TITLE
lowercase grid letters error " subscript out of bounds"

### ISSUE THREAD

**Issue by bogsnork** [cvitolo/r_rnrfa#12]
https://github.com/cvitolo/rnrfa/blob/d097be3a2582b641ff55ae4ac5d7b6b9afed96e2/R/osg_parse.R#L54

I've been using your osg_parse function (which is great) on large numbers of OS grid references.  One of my files returned the following error:
```r
#> Error in offset1[letter[, 1], , drop = FALSE]: subscript out of bounds
```
I tracked it down to a few lowercase grid letters and managed to fix it by making the grid reference vector uppercase with `toupper()`.  Would be great if you could incorporate that into the function.  Example below: 
``` r
# sample grid refs with a lowercase grid letter
data <- c("ST555780", "sT45", "ST28", "ST5566", "ST45", "ST43236136")

#generate eastings and northings
rnrfa::osg_parse(gridRefs = data)
#> Error in offset1[letter[, 1], , drop = FALSE]: subscript out of bounds
```
Example with fix: 
```r
# sample grid refs with a lowercase grid letter
data <- c("ST555780", "sT45", "ST28", "ST5566", "ST45", "ST43236136")

# convert to uppercase
data <- toupper(data)

#generate eastings and northings
rnrfa::osg_parse(gridRefs = data)
#> $easting
#> [1] 355500 340000 320000 355000 340000 343230
#> 
#> $northing
#> [1] 178000 150000 180000 166000 150000 161360
```

p.s. this is my first ever issue on someone else's repository!

**Comment by BeckyTrippier** [comment]
Thank you for raising this! I have now updated the script to fix this so it should be able to handle a mixture of upper and lower case letters in "OSGR".  Best wishes, Becky.

**Comment by bogsnork** [comment]
Thanks @BeckyTrippier.  
@cvitolo, to explain: your function ```osg_parse``` is used in [github.com/jncc/sdms/](https://github.com/jncc/sdms/) (e.g. at [this line](https://github.com/jncc/sdms/blob/f1ff0e4efca0698ee4ef53f074136b9129a37158/R/FunctionBNGdataprep.R#L110 ) and others)
 which is where I encountered the issue.

**Comment by cvitolo** [comment]
Many thanks @bogsnork! This change is now included in the latest version and you are acknowledged in the NEWS.md :)
