### ISSUE TITLE
PROJ 6 failures in rnfra

### ISSUE THREAD

**Issue by rsbivand** [cvitolo/r_rnrfa#15]
I'm testing rgdal and its reverse dependencies with PROJ 6 and -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H. The CRS offered by PROJ >= 6 are changing, so that even though rgdal is still using the proj_api.h interface (for a few more months), the underlying CRS parameters are changing. Since few are using PROJ 6 yet, you have some time to fix this as rgdal will be built with < PROJ 6 metadata files in most cases. However, PROJ 6 was released 1 March, so you'll need to adapt. I attach my check files:

[testthat.Rout.zip](https://github.com/cvitolo/rnrfa/files/2951421/testthat.Rout.zip)
[00check.log](https://github.com/cvitolo/rnrfa/files/2951422/00check.log)

**Comment by rsbivand** [comment]
Issue still present in PROJ 6.1.0

**Comment by rsbivand** [comment]
Issue still present in PROJ 6.2.0

**Comment by cvitolo** [comment]
Thanks @rsbivand, and apologies for responding so late. The cause of failure was an obsolete test, which has now been removed. The package no longer fails with PROJ 6.
