### ISSUE TITLE
OSGparse command does not support grid reference of variable length

### ISSUE THREAD

**Issue by ambroisebaker** [cvitolo/r_rnrfa#3]
Hi, I have use this command to obtain eastings and northings from GB grid references. Many worked well but I believe your code does not support Grid references of variable length (TL03, TL03Z, TL048380, ...), but maybe it wasn't intended to support these? 
Best Wishes
Ambroise

**Comment by cvitolo** [comment]
This is fixed now. 

@mikerspencer updated the function OSGparse to work with grid references of different lengths. 

I'm closing this issue.
