### ISSUE TITLE
Potential for RNRFA specific parameter in API url requests?

### ISSUE THREAD

**Issue by mattfry-ceh** [cvitolo/r_rnrfa#31]
As the use of the NRFA API increases it's increasingly hard to keep track of what it's major uses are, which we need to do to understand impact and also to focus future developments. 

Would it be possible to modify the url requests to add a parameter that allowed NRFA to log which requests are made via the RNRFA package?

We are planning on adding an equivalent parameter to requests from the other known major users, e.g. UK Water Resources Portal, NRFA website, Trends explorer tool, etc. This would simply be included as a total within our annual reporting, e.g. https://nrfa.ceh.ac.uk/news-and-media/news/nrfa-review-year-20202021 . 

This would be something like ?source=rnrfa on the end of the current queries. It might be worthwhile including the version number if this is possible as it may help to make decisions about supporting older versions of the API.

Just to be clear, we have no intention whatsoever of limiting access to data via our APIs, in fact we are hoping to increase the availability of data from new APIs e.g. sub-daily flows, which is why we want to know more about which tools the usage is coming from. I see the provision of data via packages like RNRFA as being one of the main ways we provide data to researchers in future.

**Comment by ilapros** [comment]
Hi Matt - 
This should be feasible to do - we already use a user agent in the [GET call](https://github.com/cvitolo/rnrfa/blob/master/R/internals.R), but it should be easy enough to change the various calls. I'll give that a try later on. 
I am not very clear on how to specify the version number (do you mean version number of rnrfa or of the API?) - I don't see an indicator for the version number in the current functions. 
Also - we can carry on the discussion here, but I have taken over the maintenance of the package so now the main page is at https://github.com/ilapros/rnrfa 
Best
Ilaria

**Comment by mattfry-ceh** [comment]
user agent should be ideal, thanks. We can take a look at how this comes through now. I was referring to the rnrfa package version number. Is that available to the code itself? If not no problem. I will close this here and start a new issue in the ilapros project if we need to discuss further once we've looked at the logs.
Thanks
Matt
