### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by rossmounce** [cvitolo/r_rnrfa#5]
Hi there,

I'm really excited to use your osg_parse function, thanks for creating & releasing this!

I've got a little bit of feedback for you on the installation process.

I'm running a xenial (Ubuntu 16.04.1 LTS) machine.

1.) There's no such thing as 
```
sudo apt-get install -y r-cran-rgdal
```
more formally "E: Package 'r-cran-rgdal' has no installation candidate"

Perhaps this requires the addition of a particular source to the Ubuntu Sources.List file?

2.) The readme on your github pages site (http://cvitolo.github.io/rnrfa/) is out of date: you have the function name as _OSGparse_ yet in the version of your package on CRAN (v1.2) I believe the function name is actually _osg_parse_

**Comment by cvitolo** [comment]
Hi @rossmounce, thanks for your feedbacks!

1) this is a valid command you just need to run `sudo add-apt-repository ppa:marutter/c2d4u
sudo apt-get update` beforehand. However you made me realise that the installation of rgdal changes from one system to another so in my README I should just mention that gdal should be pre-installed.

2) The gh-page is now updated, thanks!
