### ISSUE TITLE
grid references are not points, they are polygons (squares)

### ISSUE THREAD

**Issue by rossmounce** [cvitolo/r_rnrfa#6]
ah... now that I've checked what 'osg_parse' returns, 

```
bbb <- osg_parse("TL04", CoordSystem = "WGS84")
> bbb
$lon
[1] -0.5431594

$lat
[1] 52.04938
```

I presume this is returning the centroid point of the grid reference square?

Would it be possible to create a function that outputs the bounding box of the extent of the area, given a grid reference code (converted to latitude and longitude). I.e. I would expect four latlong co-ordinates to be output, not just one.

Does that make sense? It's simply misleading to convert a hectad area e.g. TL04 into a latlong of such precision, surely?

**Comment by mikerspencer** [comment]
Sort of. In that all spatial point data are a polygon based on the accuracy of the location. However, in practice this is simplified to being a point for nearly all purposes. In 10+ years of GIS work/research you're the first person I've come across who would like points treating as polygons. I think what you're suggesting is far more complex than the problem needs to be.

Perhaps an answer lies in writing to terminal the assumed accuracy from the precision of input data? Something around line 85 based on `n` would be able to tell you the assumed error/accuracy.

**Comment by rossmounce** [comment]
I can agree that an 8 or 10 digit grid reference number could be safely approximated to a point for many use cases, but in the example I gave "TL04" gets converted to lat and longs with 5 decimal place precision! Surely that gives a false sense of exactness?

Also if I'm not mistaken, by looking at the Eastings & Northings returned it looks as if osg_parse returns the South-West corner of the grid-reference as the 'point' estimate, not the centre of the grid reference. Is that standard practice? Doesn't seem logical to me. 

If a recorder only roughly knows where they are within grid square SU42, they (rightly) record "SU42" on their sheet. The point within SU42 that after-the-fact probabilistically is most likely to be nearest to where the recorder might have been in SU42 is the centre: Easting 445000 Northing 125000

yet `osg_parse("SU42")` gives $easting 440000 $northing 120000  (which is the extreme southwest corner point of grid square SU42 isn't it)?

**Comment by cvitolo** [comment]
@rossmounce In the British National Grid the reference encodes the distance from the origin of the system, not the centroid of the tile. By convention the origin is the most south-west corner, for this reason gridref=SV corresponds to X=0 Y=0. Hope this clarifies why it is correct to translate the grid reference to a point, not a polygon.   

If you want to read more about BNG, I suggest this page and related documents on the Ordnance Survey website: https://www.ordnancesurvey.co.uk/resources/maps-and-geographic-resources/the-national-grid.html.

Re your request for a function that outputs the bounding box of the extent of the area, it is a relatively easy task but does not fit the scope of this package.
