### ISSUE TITLE
Support for Irish Grid References (N.I. is within the UK)

### ISSUE THREAD

**Issue by rossmounce** [cvitolo/r_rnrfa#7]
Apologies if you consider this out of scope but since Northern Ireland is within the UK, it would seem legitimate to me...

I have some Irish Grid References I'd like to convert to latlongs with `osg_parse()`, would it be possible to add Irish Grid References as a parameter/option to CoordSystem?

Reference: https://en.wikipedia.org/wiki/Irish_grid_reference_system

**Comment by cvitolo** [comment]
Hi @rossmounce, thanks for your suggestion. The Irish Grid Reference is not used by the National River Flow Archive, therefore out of scope for this package. I'm sure this feature could be of interest for other people but should really be part of another package.
