### ISSUE TITLE
get_ts default values not specified 

### ISSUE THREAD

**Issue by Xifip** [cvitolo/r_rnrfa#8]
Hi @cvitolo,

Thanks for the package, it looks quite useful.

When running the plot_rain_flow() function I am seeing an error that default values for get_ts() are not specified.

`plot_rain_flow(id = 54090)`

returns the error:
_Error in get_ts(id, type = "cmr") : 
  argument "metadata" is missing, with no default_

I suggest that the defaults should be added to the get_ts function:

`get_ts <- function(id, type, metadata, cl, verbose){ ... }`

changed to:

`get_ts <- function(id, type, metadata = FALSE, cl, verbose = FALSE){ ... }`

**Comment by cvitolo** [comment]
@Xifip many thanks for the suggestion!

I have changed the default arguments based on your suggestions.
