### ISSUE TITLE
get_ts() does not supply station id's in "parallel-mode"

### ISSUE THREAD

**Issue by the-Hull** [cvitolo/r_rnrfa#9]
Hi Claudia,

this is a great package, thanks for developing. 

I found a minor issue with get_ts() where station id names are not returned when supplying 'cl' with a cluster object. It is easily fixed by adding another line (`names(tsList) <- id)`) into one of the if-statements of the function's definition (as is the case when !is.null(cl) == FALSE)

A minimal reproducible example below:

```# MRE
library(rnrfa)
library(parallel)

# Filter stations based on identification number
someStations <- catalogue(columnName="id",
                          columnValue=c(3001,3002,3003))

# Use detectCores() to find out many cores are available on your machine
cl <- makeCluster(getOption("cl.cores", detectCores() ))



# Get flow data with a sequential approach
system.time( s1 <- gdf(someStations$id, cl = NULL) )

# Get flow data with a concurrent approach (using `parLapply()`)
system.time( s2 <- gdf(id = someStations$id, cl = cl) )  

# Check for output names
identical(names(s1), names(s2))
```

All the best,
Alex

**Comment by cvitolo** [comment]
Thanks for spotting this!

Merged your pull request and going to close this issue
